#' Converte os CID-O de 4 Dígitos de Um Dataframe
#'
#' Esta função mapeia os códigos CID  de 4 dígitos para seus nomes completos na coluna `Localizacao_Primaria_4D` de um dataframe. Os nomes completos dos CID-O de 4 dígitos são adicionados em uma nova coluna `CID4d`.
#'
#' @param dados Um dataframe contendo a coluna `Localizacao_Primaria_4D`.
#' @return Retorna um dataframe com os nomes completos dos CID-O  de 4 dígitos adicionados em uma nova coluna.
#' @export
#' @name renomear_CID_4digitos
#' @examples
#' # Escreva o nome do dataframe e execute a função. Se seu dataframe for "dados_RHC_combinados", use a funçao como:
#'
#' dados_RHC_combinados <- renomear_CID_4digitos(dados_RHC_combinados)
renomear_CID_4digitos <- function(dados) {
  message("Iniciando o ajuste dos códigos CID-O de 4 dígitos para nomes completos.")

  # Definição do dataframe de mapeamento de CID para nomes
  cid_names <- data.frame(
    CID = c("C00.0", "C00.1", "C00.2", "C00.3", "C00.4", "C00.5", "C00.6", "C00.8", "C00.9", "C01", "C02.0", "C02.1", "C02.2", "C02.3", "C02.4", "C02.8", "C02.9", "C03.0", "C03.1", "C03.9", "C04.0", "C04.1", "C04.8", "C04.9", "C05.0", "C05.1", "C05.2", "C05.8", "C05.9", "C06.0",
            "C06.1", "C06.2", "C06.8", "C06.9", "C07", "C08.0", "C08.1", "C08.8", "C08.9", "C09.0", "C09.1", "C09.8", "C09.9", "C10.0", "C10.1", "C10.2", "C10.3", "C10.4", "C10.8", "C10.9", "C11.0", "C11.1", "C11.2", "C11.3", "C11.8", "C11.9", "C12", "C13.0", "C13.1", "C13.2",
            "C13.8", "C13.9", "C14.0", "C14.2", "C14.8", "C15.0", "C15.1", "C15.2", "C15.3", "C15.4", "C15.5", "C15.8", "C15.9", "C16.0", "C16.1", "C16.2", "C16.3", "C16.4", "C16.5", "C16.6", "C16.8", "C16.9", "C17.0", "C17.1", "C17.2", "C17.3", "C17.8", "C17.9", "C18.0", "C18.1",
            "C18.2", "C18.3", "C18.4", "C18.5", "C18.6", "C18.7", "C18.8", "C18.9", "C19", "C20", "C21.0", "C21.1", "C21.2", "C21.8", "C22.0", "C22.1", "C22.2", "C22.3", "C22.4", "C22.7", "C22.9", "C23", "C24.0", "C24.1", "C24.8", "C24.9", "C25.0", "C25.1", "C25.2", "C25.3",
            "C25.4", "C25.7", "C25.8", "C25.9", "C26.0", "C26.1", "C26.8", "C26.9", "C30.0", "C30.1", "C31.0", "C31.1", "C31.2", "C31.3", "C31.8", "C31.9", "C32.0", "C32.1", "C32.2", "C32.3", "C32.8", "C32.9", "C33", "C34.0", "C34.1", "C34.2", "C34.3", "C34.8", "C34.9", "C37",
            "C38.0", "C38.1", "C38.2", "C38.3", "C38.4", "C38.8", "C39.0", "C39.8", "C39.9", "C40.0", "C40.1", "C40.2", "C40.3", "C40.8", "C40.9", "C41.0", "C41.1", "C41.2", "C41.3", "C41.4", "C41.8", "C41.9", "C42.1", "C43.0", "C43.1", "C43.2", "C43.3", "C43.4", "C43.5", "C43.6",
            "C43.7", "C43.8", "C43.9", "C44.0", "C44.1", "C44.2", "C44.3", "C44.4", "C44.5", "C44.6", "C44.7", "C44.8", "C44.9", "C45.0", "C45.1", "C45.2", "C45.7", "C45.9", "C46.0", "C46.1", "C46.2", "C46.3", "C46.7", "C46.8", "C46.9", "C47.0", "C47.1", "C47.2", "C47.3", "C47.4",
            "C47.5", "C47.6", "C47.8", "C47.9", "C48.0", "C48.1", "C48.2", "C48.8", "C49.0", "C49.1", "C49.2", "C49.3", "C49.4", "C49.5", "C49.6", "C49.8", "C49.9", "C50.0", "C50.1", "C50.2", "C50.3", "C50.4", "C50.5", "C50.6", "C50.8", "C50.9", "C51.0", "C51.1", "C51.2", "C51.8",
            "C51.9", "C52", "C53.0", "C53.1", "C53.8", "C53.9", "C54.0", "C54.1", "C54.2", "C54.3", "C54.8", "C54.9", "C55", "C56", "C57.0", "C57.1", "C57.2", "C57.3", "C57.4", "C57.7", "C57.8", "C57.9", "C58", "C60.0", "C60.1", "C60.2", "C60.8", "C60.9", "C61", "C62.0",
            "C62.1", "C62.9", "C63.0", "C63.1", "C63.2", "C63.7", "C63.8", "C63.9", "C64", "C65", "C66", "C67.0", "C67.1", "C67.2", "C67.3", "C67.4", "C67.5", "C67.6", "C67.7", "C67.8", "C67.9", "C68.0", "C68.1", "C68.8", "C68.9", "C69.0", "C69.1", "C69.2", "C69.3", "C69.4",
            "C69.5", "C69.6", "C69.8", "C69.9", "C70.0", "C70.1", "C70.9", "C71.0", "C71.1", "C71.2", "C71.3", "C71.4", "C71.5", "C71.6", "C71.7", "C71.8", "C71.9", "C72.0", "C72.1", "C72.2", "C72.3", "C72.4", "C72.5", "C72.8", "C72.9", "C73", "C74.0", "C74.1", "C74.9", "C75.0",
            "C75.1", "C75.2", "C75.3", "C75.4", "C75.5", "C75.8", "C75.9", "C76.0", "C76.1", "C76.2", "C76.3", "C76.4", "C76.5", "C76.7", "C76.8", "C77.0", "C77.1", "C77.2", "C77.3", "C77.4", "C77.5", "C77.8", "C77.9", "C78.0", "C78.1", "C78.2", "C78.3", "C78.4", "C78.5", "C78.6",
            "C78.7", "C78.8", "C79.0", "C79.1", "C79.2", "C79.3", "C79.4", "C79.5", "C79.6", "C79.7", "C79.8", "C80", "C81.0", "C81.1", "C81.2", "C81.3", "C81.7", "C81.9", "C82.0", "C82.1", "C82.2", "C82.7", "C82.9", "C83.0", "C83.1", "C83.2", "C83.3", "C83.4", "C83.5", "C83.6",
            "C83.7", "C83.8", "C83.9", "C84.0", "C84.1", "C84.2", "C84.3", "C84.4", "C84.5", "C85.0", "C85.1", "C85.7", "C85.9", "C88.0", "C88.1", "C88.2", "C88.3", "C88.7", "C88.9", "C90.0", "C90.1", "C90.2", "C91.0", "C91.1", "C91.2", "C91.3", "C91.4", "C91.5", "C91.7", "C91.9",
            "C92.0", "C92.1", "C92.2", "C92.3", "C92.4", "C92.5", "C92.7", "C92.9", "C93.0", "C93.1", "C93.2", "C93.7", "C93.9", "C94.0", "C94.1", "C94.2", "C94.3", "C94.4", "C94.5", "C94.7", "C95.0", "C95.1", "C95.2", "C95.7", "C95.9", "C96.0", "C96.1", "C96.2", "C96.3", "C96.7",
            "C96.9", "C97", "D00.0", "D00.1", "D00.2", "D01.0", "D01.1", "D01.2", "D01.3", "D01.4", "D01.5", "D01.7", "D01.9", "D02.0", "D02.1", "D02.2", "D02.3", "D02.9", "D03.0", "D03.1", "D03.2", "D03.3", "D03.4", "D03.5", "D03.6", "D03.7", "D03.8", "D03.9", "D04.0", "D04.1",
            "D04.2", "D04.3", "D04.4", "D04.5", "D04.6", "D04.7", "D04.8", "D04.9", "D05.0", "D05.1", "D05.7", "D05.9", "D06.0", "D06.1", "D06.7", "D06.9", "D07.0", "D07.1", "D07.2", "D07.3", "D07.4", "D07.5", "D07.6", "D09.0", "D09.1", "D09.2", "D09.3", "D09.7", "D09.9", "D10.0",
            "D10.1", "D10.2", "D10.3", "D10.4", "D10.5", "D10.6", "D10.7", "D10.9", "D11.0", "D11.7", "D11.9", "D12.0", "D12.1", "D12.2", "D12.3", "D12.4", "D12.5", "D12.6", "D12.7", "D12.8", "D12.9", "D13.0", "D13.1", "D13.2", "D13.3", "D13.4", "D13.5", "D13.6", "D13.7", "D13.9",
            "D14.0", "D14.1", "D14.2", "D14.3", "D14.4", "D15.0", "D15.1", "D15.2", "D15.7", "D15.9", "D16.0", "D16.1", "D16.2", "D16.3", "D16.4", "D16.5", "D16.6", "D16.7", "D16.8", "D16.9", "D17.0", "D17.1", "D17.2", "D17.3", "D17.4", "D17.5", "D17.6", "D17.7", "D17.9", "D18.0", "D18.1",
            "D19.0", "D19.1", "D19.7", "D19.9", "D20.0", "D20.1", "D21.0", "D21.1", "D21.2", "D21.3", "D21.4", "D21.5", "D21.6", "D21.9", "D22.0", "D22.1", "D22.2", "D22.3", "D22.4", "D22.5", "D22.6", "D22.7", "D22.9", "D23.0", "D23.1", "D23.2", "D23.3", "D23.4", "D23.5", "D23.6",
            "D23.7", "D23.9", "D24", "D25.0", "D25.1", "D25.2", "D25.9", "D26.0", "D26.1", "D26.7", "D26.9", "D27", "D28.0", "D28.1", "D28.2", "D28.7", "D28.9", "D29.0", "D29.1", "D29.2", "D29.3", "D29.4", "D29.7", "D29.9", "D30.0", "D30.1", "D30.2", "D30.3", "D30.4", "D30.7",
            "D30.9", "D31.0", "D31.1", "D31.2", "D31.3", "D31.4", "D31.5", "D31.6", "D31.9", "D32.0", "D32.1", "D32.9", "D33.0", "D33.1", "D33.2", "D33.3", "D33.4", "D33.7", "D33.9", "D34", "D35.0", "D35.1", "D35.2", "D35.3", "D35.4", "D35.5", "D35.6", "D35.7", "D35.8", "D35.9",
            "D36.0", "D36.1", "D36.7", "D36.9", "D37.0", "D37.1", "D37.2", "D37.3", "D37.4", "D37.5", "D37.6", "D37.7", "D37.9", "D38.0", "D38.1", "D38.2", "D38.3", "D38.4", "D38.5", "D38.6", "D39.0", "D39.1", "D39.2", "D39.7", "D39.9", "D40.0", "D40.1", "D40.7", "D40.9", "D41.0",
            "D41.1", "D41.2", "D41.3", "D41.4", "D41.7", "D41.9", "D42.0", "D42.1", "D42.9", "D43.0", "D43.1", "D43.2", "D43.3", "D43.4", "D43.7", "D43.9", "D44.0", "D44.1", "D44.2", "D44.3", "D44.4", "D44.5", "D44.6", "D44.7", "D44.8", "D44.9", "D45", "D46.0", "D46.1", "D46.2",
            "D46.3", "D46.4", "D46.7", "D46.9", "D47.0", "D47.1", "D47.2", "D47.3", "D47.7", "D47.9", "D48.0", "D48.1", "D48.2", "D48.3", "D48.4", "D48.5", "D48.6", "D48.7", "D48.9",
            "C65.9", "C19.9", "C12.9", "C07.9", "C01.9", "C37.9", "C23.9", "C20.9", "C52.9", "C55.9", "C56.0", "C56.9", "C80.9", "C73.9", "C66.9", "C61.9", "C61.2", "C61.", "C64.9", "C64.", "C62", "C42.4", "C42.2", "C42.0", "C42.3", "C58.9"),
    NOME = c("Neoplasia maligna do lábio superior externo",
             "Neoplasia maligna do lábio inferior externo",
             "Neoplasia maligna do lábio externo, não especificado",
             "Neoplasia maligna do lábio superior, face interna",
             "Neoplasia maligna do lábio inferior, face interna",
             "Neoplasia maligna do lábio, sem especificação, face interna",
             "Neoplasia maligna da comissura labial",
             "Neoplasia maligna do lábio com lesão invasiva",
             "Neoplasia maligna do lábio, não especificado",
             "Neoplasia maligna da base da língua",
             "Neoplasia maligna da face dorsal da língua",
             "Neoplasia maligna da borda da língua",
             "Neoplasia maligna da face ventral da língua",
             "Neoplasia maligna de dois terços anteriores da língua, parte não especificada",
             "Neoplasia maligna da amígdala lingual",
             "Neoplasia maligna da língua com lesão invasiva",
             "Neoplasia maligna da língua, não especificada",
             "Neoplasia maligna da gengiva superior",
             "Neoplasia maligna da gengiva inferior",
             "Neoplasia maligna da gengiva, não especificada",
             "Neoplasia maligna do assoalho anterior da boca",
             "Neoplasia maligna do assoalho lateral da boca",
             "Neoplasia maligna do assoalho da boca com lesão invasiva",
             "Neoplasia maligna do assoalho da boca, não especificado",
             "Neoplasia maligna do palato duro",
             "Neoplasia maligna do palato mole",
             "Neoplasia maligna da úvula",
             "Neoplasia maligna do palato com lesão invasiva",
             "Neoplasia maligna do palato, não especificado",
             "Neoplasia maligna da mucosa oral",
             "Neoplasia maligna do vestíbulo da boca",
             "Neoplasia maligna da área retromolar",
             "Neoplasia maligna de outras partes e de partes não especificadas da boca com lesão invasiva",
             "Neoplasia maligna da boca, não especificada",
             "Neoplasia maligna da glândula parótida",
             "Neoplasia maligna da glândula submandibular",
             "Neoplasia maligna da glândula sublingual",
             "Neoplasia maligna das glândulas salivares maiores com lesão invasiva",
             "Neoplasia maligna da glândula salivar maior, não especificada",
             "Neoplasia maligna da fossa amigdaliana",
             "Neoplasia maligna do pilar amigdaliano (anterior) (posterior)",
             "Neoplasia maligna da amígdala com lesão invasiva",
             "Neoplasia maligna da amígdala, não especificada",
             "Neoplasia maligna da valécula",
             "Neoplasia maligna da face anterior da epiglote",
             "Neoplasia maligna da parede lateral da orofaringe",
             "Neoplasia maligna da parede posterior da orofaringe",
             "Neoplasia maligna da fenda branquial",
             "Neoplasia maligna da orofaringe com lesão invasiva",
             "Neoplasia maligna da orofaringe, não especificada",
             "Neoplasia maligna da parede superior da nasofaringe",
             "Neoplasia maligna da parede posterior da nasofaringe",
             "Neoplasia maligna da parede lateral da nasofaringe",
             "Neoplasia maligna da parede anterior da nasofaringe",
             "Neoplasia maligna da nasofaringe com lesão invasiva",
             "Neoplasia maligna da nasofaringe, não especificada",
             "Neoplasia maligna do seio piriforme",
             "Neoplasia maligna da região pós-cricóidea",
             "Neoplasia maligna da prega ariepiglótica, face hipofaríngea",
             "Neoplasia maligna da parede posterior da hipofaringe",
             "Neoplasia maligna da hipofaringe com lesão invasiva",
             "Neoplasia maligna da hipofaringe, não especificada",
             "Neoplasia maligna da faringe, não especificada",
             "Neoplasia maligna do anel de Waldeyer",
             "Neoplasia maligna do lábio, cavidade oral e faringe com lesão invasiva",
             "Neoplasia maligna da porção cervical do esôfago (esôfago cervical)",
             "Neoplasia maligna da porção torácica do esôfago (esôfago torácico)",
             "Neoplasia maligna da porção abdominal do esôfago (esôfago abdominal)",
             "Neoplasia maligna do terço superior do esôfago",
             "Neoplasia maligna do terço médio do esôfago",
             "Neoplasia maligna do terço inferior do esôfago",
             "Neoplasia maligna do esôfago com lesão invasiva",
             "Neoplasia maligna do esôfago, não especificado",
             "Neoplasia maligna da cárdia",
             "Neoplasia maligna do fundo do estômago",
             "Neoplasia maligna do corpo do estômago",
             "Neoplasia maligna do antro pilórico",
             "Neoplasia maligna do piloro",
             "Neoplasia maligna da pequena curvatura do estômago, não especificada",
             "Neoplasia maligna da grande curvatura do estômago, não especificada",
             "Neoplasia maligna do estômago com lesão invasiva",
             "Neoplasia maligna do estômago, não especificado",
             "Neoplasia maligna do duodeno",
             "Neoplasia maligna do jejuno",
             "Neoplasia maligna do íleo",
             "Neoplasia maligna do divertículo de Meckel",
             "Neoplasia maligna do intestino delgado com lesão invasiva",
             "Neoplasia maligna do intestino delgado, não especificado",
             "Neoplasia maligna do ceco",
             "Neoplasia maligna do apêndice (vermiforme)",
             "Neoplasia maligna do cólon ascendente",
             "Neoplasia maligna da flexura (ângulo) hepática(o)",
             "Neoplasia maligna do cólon transverso",
             "Neoplasia maligna da flexura (ângulo) esplênica(o)",
             "Neoplasia maligna do cólon descendente",
             "Neoplasia maligna do cólon sigmóide",
             "Neoplasia maligna do cólon com lesão invasiva",
             "Neoplasia maligna do cólon, não especificado",
             "Neoplasia maligna da junção retossigmóide",
             "Neoplasia maligna do reto",
             "Neoplasia maligna do ânus, não especificado",
             "Neoplasia maligna do canal anal",
             "Neoplasia maligna da zona cloacogênica",
             "Neoplasia maligna do reto, ânus e do canal anal com lesão invasiva",
             "Carcinoma de células hepáticas",
             "Carcinoma de vias biliares intra-hepáticas",
             "Hepatoblastoma",
             "Angiossarcoma do fígado",
             "Outros sarcomas do fígado",
             "Outros carcinomas especificados do fígado",
             "Neoplasia maligna do fígado, não especificada",
             "Neoplasia maligna da vesícula biliar",
             "Neoplasia maligna das vias biliares extra-hepáticas",
             "Neoplasia maligna da ampola de Vater",
             "Neoplasia maligna das vias biliares com lesão invasiva",
             "Neoplasia maligna da via biliar, não especificada",
             "Neoplasia maligna da cabeça do pâncreas",
             "Neoplasia maligna do corpo do pâncreas",
             "Neoplasia maligna da cauda do pâncreas",
             "Neoplasia maligna do canal pancreático",
             "Neoplasia maligna do pâncreas endócrino",
             "Neoplasia maligna de outras partes do pâncreas",
             "Neoplasia maligna do pâncreas com lesão invasiva",
             "Neoplasia maligna do pâncreas, não especificado",
             "Neoplasia maligna do trato intestinal, parte não especificada",
             "Neoplasia maligna do baço",
             "Neoplasia maligna do aparelho digestivo com lesão invasiva",
             "Neoplasia maligna de localizações mal definidas dentro do aparelho digestivo",
             "Neoplasia maligna da cavidade nasal",
             "Neoplasia maligna do ouvido médio",
             "Neoplasia maligna do seio maxilar",
             "Neoplasia maligna do seio etmoidal",
             "Neoplasia maligna do seio frontal",
             "Neoplasia maligna do seio esfenoidal",
             "Neoplasia maligna dos seios da face com lesão invasiva",
             "Neoplasia maligna do seio da face, não especificado",
             "Neoplasia maligna da glote",
             "Neoplasia maligna da região supraglótica",
             "Neoplasia maligna da região subglótica",
             "Neoplasia maligna das cartilagens da laringe",
             "Neoplasia maligna da laringe com lesão invasiva",
             "Neoplasia maligna da laringe, não especificada",
             "Neoplasia maligna da traquéia",
             "Neoplasia maligna do brônquio principal",
             "Neoplasia maligna do lobo superior, brônquio ou pulmão",
             "Neoplasia maligna do lobo médio, brônquio ou pulmão",
             "Neoplasia maligna do lobo inferior, brônquio ou pulmão",
             "Neoplasia maligna dos brônquios e dos pulmões com lesão invasiva",
             "Neoplasia maligna dos brônquios ou pulmões, não especificado",
             "Neoplasia maligna do timo",
             "Neoplasia maligna do coração",
             "Neoplasia maligna do mediastino anterior",
             "Neoplasia maligna do mediastino posterior",
             "Neoplasia maligna do mediastino, porção não especificada",
             "Neoplasia maligna da pleura",
             "Neoplasia maligna do coração, mediastino e pleura com lesão invasiva",
             "Neoplasia maligna do trato respiratório superior, porção não especificada",
             "Neoplasia maligna do aparelho respiratório e dos órgãos intratorácicos com lesão invasiva",
             "Neoplasia maligna de localizações mal definidas do aparelho respiratório",
             "Neoplasia maligna da omoplata [escápula] e ossos longos dos membros superiores",
             "Neoplasia maligna dos ossos curtos dos membros superiores",
             "Neoplasia maligna dos ossos longos dos membros inferiores",
             "Neoplasia maligna dos ossos curtos dos membros inferiores",
             "Neoplasia maligna dos ossos e cartilagens articulares dos membros com lesão invasiva",
             "Neoplasia maligna dos ossos e cartilagens articulares de membro não especificado",
             "Neoplasia maligna dos ossos do crânio e da face",
             "Neoplasia maligna da mandíbula",
             "Neoplasia maligna da coluna vertebral",
             "Neoplasia maligna das costelas, esterno e clavícula",
             "Neoplasia maligna dos ossos da pelve, sacro e cóccix",
             "Neoplasia maligna dos ossos e das cartilagens articulares com lesão invasiva",
             "Neoplasia maligna dos ossos e cartilagens articulares, não especificados",
             "Medula Óssea",
             "Melanoma maligno do lábio",
             "Melanoma maligno da pálpebra, incluindo as comissuras palpebrais",
             "Melanoma maligno da orelha e do conduto auditivo externo",
             "Melanoma maligno de outras partes e partes não especificadas da face",
             "Melanoma maligno do couro cabeludo e do pescoço",
             "Melanoma maligno do tronco",
             "Melanoma maligno do membro superior, incluindo ombro",
             "Melanoma maligno do membro inferior, incluindo quadril",
             "Melanoma maligno invasivo da pele",
             "Melanoma maligno de pele, não especificado",
             "Neoplasia maligna da pele do lábio",
             "Neoplasia maligna da pele da pálpebra, incluindo o canto",
             "Neoplasia maligna da pele da orelha e do conduto auditivo externo",
             "Neoplasia maligna da pele de outras partes e de partes não especificadas da face",
             "Neoplasia maligna da pele do couro cabeludo e do pescoço",
             "Neoplasia maligna da pele do tronco",
             "Neoplasia maligna da pele do membro superior, incluindo ombro",
             "Neoplasia maligna da pele do membro inferior, incluindo quadril",
             "Neoplasia maligna da pele com lesão invasiva",
             "Neoplasia maligna da pele, não especificada",
             "Mesotelioma da pleura",
             "Mesotelioma do peritônio",
             "Mesotelioma do pericárdio",
             "Mesotelioma de outras localizações",
             "Mesotelioma, não especificado",
             "Sarcoma de Kaposi da pele",
             "Sarcoma de Kaposi de tecidos moles",
             "Sarcoma de Kaposi do palato",
             "Sarcoma de Kaposi dos gânglios linfáticos",
             "Sarcoma de Kaposi de outras localizações",
             "Sarcoma de Kaposi de múltiplos órgãos",
             "Sarcoma de Kaposi, não especificado",
             "Neoplasia maligna dos nervos periféricos da cabeça, face e pescoço",
             "Neoplasia maligna dos nervos periféricos dos membros superiores, incluindo ombro",
             "Neoplasia maligna dos nervos periféricos dos membros inferiores, incluindo quadril",
             "Neoplasia maligna dos nervos periféricos do tórax",
             "Neoplasia maligna dos nervos periféricos do abdome",
             "Neoplasia maligna dos nervos periféricos da pelve",
             "Neoplasia maligna dos nervos periféricos do tronco",
             "Neoplasia maligna dos nervos periféricos e do sistema nervoso autônomo com lesão invasiva",
             "Neoplasia maligna dos nervos periféricos e sistema nervoso autônomo, não especificados",
             "Neoplasia maligna do retroperitônio",
             "Neoplasia maligna de partes especificadas do peritônio",
             "Neoplasia maligna do peritônio",
             "Neoplasia maligna dos tecidos moles do retroperitônio e do peritônio com lesão invasiva",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles da cabeça, face e pescoço",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles dos membros superiores, incluindo ombro",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles dos membros inferiores, incluindo quadril",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles do tórax",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles do abdome",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles da pelve",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles do tronco",
             "Neoplasia maligna do tecido conjuntivo e dos tecidos moles com lesão invasiva",
             "Neoplasia maligna do tecido conjuntivo e tecidos moles, não especificados",
             "Neoplasia maligna do mamilo e aréola",
             "Neoplasia maligna da porção central da mama",
             "Neoplasia maligna do quadrante superior interno da mama",
             "Neoplasia maligna do quadrante inferior interno da mama",
             "Neoplasia maligna do quadrante superior externo da mama",
             "Neoplasia maligna do quadrante inferior externo da mama",
             "Neoplasia maligna da porção axilar da mama",
             "Neoplasia maligna da mama com lesão invasiva",
             "Neoplasia maligna da mama, não especificada",
             "Neoplasia maligna dos grandes lábios",
             "Neoplasia maligna dos pequenos lábios",
             "Neoplasia maligna do clitóris",
             "Neoplasia maligna da vulva com lesão invasiva",
             "Neoplasia maligna da vulva, não especificada",
             "Neoplasia maligna da vagina",
             "Neoplasia maligna do endocérvix",
             "Neoplasia maligna do exocérvix",
             "Neoplasia maligna do colo do útero com lesão invasiva",
             "Neoplasia maligna do colo do útero, não especificado",
             "Neoplasia maligna do istmo do útero",
             "Neoplasia maligna do endométrio",
             "Neoplasia maligna do miométrio",
             "Neoplasia maligna do fundo do útero",
             "Neoplasia maligna do corpo do útero com lesão invasiva",
             "Neoplasia maligna do corpo do útero, não especificado",
             "Neoplasia maligna do útero, porção não especificada",
             "Neoplasia maligna do ovário",
             "Neoplasia maligna da trompa de Falópio",
             "Neoplasia maligna do ligamento largo",
             "Neoplasia maligna do ligamento redondo",
             "Neoplasia maligna do paramétrio",
             "Neoplasia maligna dos anexos uterinos",
             "Neoplasia maligna de outras partes especificadas dos órgãos genitais femininos",
             "Neoplasia maligna dos órgãos genitais femininos com lesão invasiva",
             "Neoplasia maligna de órgão genital feminino, não especificado",
             "Neoplasia maligna da placenta",
             "Neoplasia maligna do prepúcio",
             "Neoplasia maligna da glande",
             "Neoplasia maligna do corpo do pênis",
             "Neoplasia maligna do pênis com lesão invasiva",
             "Neoplasia maligna do pênis, não especificado",
             "Neoplasia maligna da próstata",
             "Neoplasia maligna do testículo criptorquídico",
             "Neoplasia maligna do testículo tópico",
             "Neoplasia maligna do testículo, sem outras especificações",
             "Neoplasia maligna do epidídimo",
             "Neoplasia maligna do cordão espermático",
             "Neoplasia maligna do escroto",
             "Neoplasia maligna de outros órgãos genitais masculinos especificados",
             "Neoplasia maligna dos órgãos genitais masculinos com lesão invasiva",
             "Neoplasia maligna de órgão genital masculino, não especificado",
             "Neoplasia maligna do rim, exceto pelve renal",
             "Neoplasia maligna da pelve renal",
             "Neoplasia maligna dos ureteres",
             "Neoplasia maligna do trígono da bexiga",
             "Neoplasia maligna da cúpula da bexiga",
             "Neoplasia maligna da parede lateral da bexiga",
             "Neoplasia maligna da parede anterior da bexiga",
             "Neoplasia maligna da parede posterior da bexiga",
             "Neoplasia maligna do colo da bexiga",
             "Neoplasia maligna do orifício uretérico",
             "Neoplasia maligna do úraco",
             "Neoplasia maligna da bexiga com lesão invasiva",
             "Neoplasia maligna da bexiga, sem outra especificações",
             "Neoplasia maligna da uretra",
             "Neoplasia maligna da glândula parauretral",
             "Neoplasia maligna dos órgãos urinários com lesão invasiva",
             "Neoplasia maligna de órgão urinário, não especificado",
             "Neoplasia maligna da conjuntiva",
             "Neoplasia maligna da córnea",
             "Neoplasia maligna da retina",
             "Neoplasia maligna da coróide",
             "Neoplasia maligna do corpo ciliar",
             "Neoplasia maligna da glândula e canal lacrimal",
             "Neoplasia maligna da órbita",
             "Neoplasia maligna do olho e anexos com lesão invasiva",
             "Neoplasia maligna do olho, não especificado",
             "Neoplasia maligna das meninges cerebrais",
             "Neoplasia maligna das meninges espinhais",
             "Neoplasia maligna da meninge, não especificada",
             "Neoplasia maligna do cérebro, exceto lobos e ventrículos",
             "Neoplasia maligna do lobo frontal",
             "Neoplasia maligna do lobo temporal",
             "Neoplasia maligna do lobo parietal",
             "Neoplasia maligna do lobo occipital",
             "Neoplasia maligna do ventrículo cerebral",
             "Neoplasia maligna do cerebelo",
             "Neoplasia maligna do tronco cerebral",
             "Neoplasia maligna do encéfalo com lesão invasiva",
             "Neoplasia maligna do encéfalo, não especificado",
             "Neoplasia maligna da medula espinhal",
             "Neoplasia maligna da cauda eqüina",
             "Neoplasia maligna do nervo olfativo",
             "Neoplasia maligna do nervo óptico",
             "Neoplasia maligna do nervo acústico",
             "Neoplasia maligna de outros nervos cranianos e os não especificados",
             "Neoplasia maligna do encéfalo e de outras partes do sistema nervoso central com lesão invasiva",
             "Neoplasia maligna do sistema nervoso central, não especificado",
             "Neoplasia maligna da glândula tireóide",
             "Neoplasia maligna do córtex da supra-renal",
             "Neoplasia maligna da medula da supra-renal",
             "Neoplasia maligna da glândula supra-renal, não especificada",
             "Neoplasia maligna da glândula paratireóide",
             "Neoplasia maligna da glândula hipófise (pituitária)",
             "Neoplasia maligna do conduto craniofaríngeo",
             "Neoplasia maligna da glândula pineal",
             "Neoplasia maligna do corpo carotídeo",
             "Neoplasia maligna do corpo aórtico e outros paragânglios",
             "Neoplasia maligna com comprometimento pluriglandular, sem outra especificação",
             "Neoplasia maligna de glândula endócrina, não especificada",
             "Neoplasia maligna da cabeça, face e pescoço",
             "Neoplasia maligna do tórax",
             "Neoplasia maligna do abdome",
             "Neoplasia maligna da pelve",
             "Neoplasia maligna do membro superior",
             "Neoplasia maligna do membro inferior",
             "Neoplasia maligna de outras localizações mal definidas",
             "Neoplasia maligna de outras localizações e das mal definidas com lesão invasiva",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos da cabeça, face e pescoço",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos intratorácicos",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos intra-abdominais",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos axilares e dos membros superiores",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos inguinais e dos membros inferiores",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos intrapélvicos",
             "Neoplasia maligna secundária e não especificada dos gânglios linfáticos de múltiplas regiões",
             "Neoplasia maligna secundária e não especificada de gânglio linfático, não especificado",
             "Neoplasia maligna secundária dos pulmões",
             "Neoplasia maligna secundária do mediastino",
             "Neoplasia maligna secundária da pleura",
             "Neoplasia maligna secundária de outros órgãos respiratórios e não especificados",
             "Neoplasia maligna secundária do intestino delgado",
             "Neoplasia maligna secundária do intestino grosso e do reto",
             "Neoplasia maligna secundária do retroperitônio e do peritônio",
             "Neoplasia maligna secundária do fígado",
             "Neoplasia maligna secundária de outros órgãos digestivos e não especificados",
             "Neoplasia maligna secundária do rim e da pelve renal",
             "Neoplasia maligna secundária da bexiga, de outro órgão urinário e não especificado",
             "Neoplasia maligna secundária da pele",
             "Neoplasia maligna secundária do encéfalo e das meninges cerebrais",
             "Neoplasia maligna secundária de outras partes do sistema nervoso e não especificadas",
             "Neoplasia maligna secundária dos ossos e da medula óssea",
             "Neoplasia maligna secundária do ovário",
             "Neoplasia maligna secundária das glândulas supra-renais (adrenais)",
             "Neoplasia maligna secundária de outra localização especificada",
             "Neoplasia maligna, sem especificação de localização",
             "Doença de Hodgkin, predominância linfocítica",
             "Doença de Hodgkin, esclerose nodular",
             "Doença de Hodgkin, celularidade mista",
             "Doença de Hodgkin, depleção linfocítica",
             "Outra forma da doença de Hodgkin",
             "Doença de Hodgkin, não especificada",
             "Linfoma não-Hodgkin, pequenas células clivadas, folicular",
             "Linfoma não-Hodgkin, misto, de pequenas e grandes células clivadas, folicular",
             "Linfoma não-Hodgkin, grandes células, folicular",
             "Outros tipos de linfoma não-Hodgkin, folicular",
             "Linfoma não-Hodgkin, folicular, não especificado",
             "Linfoma não-Hodgkin difuso, pequenas células (difuso)",
             "Linfoma não-Hodgkin difuso, pequenas células clivadas (difuso)",
             "Linfoma não-Hodgkin difuso, misto, de pequenas e grandes células (difuso)",
             "Linfoma não-Hodgkin difuso, grandes células (difuso)",
             "Linfoma não-Hodgkin difuso, imunoblástico (difuso)",
             "Linfoma não-Hodgkin difuso, linfoblástico (difuso)",
             "Linfoma não-Hodgkin difuso, indiferenciado (difuso)",
             "Tumor de Burkitt",
             "Outros tipos de linfoma não-Hodgkin difuso",
             "Linfoma não-Hodgkin difuso, não especificado",
             "Micose fungóide",
             "Doença de Sézary",
             "Linfoma da zona T",
             "Linfoma linfoepitelióide",
             "Linfoma de células T, periférico",
             "Outros linfomas de células T e os não especificados",
             "Linfossarcoma",
             "Linfoma de células B, não especificado",
             "Outros tipos especificados de linfoma não-Hodgkin",
             "Linfoma não-Hodgkin de tipo não especificado",
             "Macroglobulinemia de Waldenström",
             "Doença de cadeia pesada alfa",
             "Doença de cadeia pesada gama",
             "Doença imunoproliferativa do intestino delgado",
             "Outras doenças imunoproliferativas malignas",
             "Doença imunoproliferativa maligna, não especificada",
             "Mieloma múltiplo",
             "Leucemia plasmocitária",
             "Plasmocitoma extramedular",
             "Leucemia linfoblástica aguda",
             "Leucemia linfocítica crônica",
             "Leucemia linfocítica subaguda",
             "Leucemia pró-linfocítica",
             "Leucemia de células pilosas",
             "Leucemia de células T do adulto",
             "Outras leucemias linfóides",
             "Leucemia linfóide, não especificada",
             "Leucemia mielóide aguda",
             "Leucemia mielóide crônica",
             "Leucemia mielóide subaguda",
             "Sarcoma mielóide",
             "Leucemia pró-mielocítica aguda",
             "Leucemia mielomonocítica aguda",
             "Outras leucemias mielóides",
             "Leucemia mielóide, não especificada",
             "Leucemia monocítica aguda",
             "Leucemia monocítica crônica",
             "Leucemia monocítica subaguda",
             "Outras leucemias monocíticas",
             "Leucemia monocítica, não especificada",
             "Eritremia e eritroleucemia agudas",
             "Eritremia crônica",
             "Leucemia megacarioblástica aguda",
             "Leucemia de mastócitos",
             "Panmielose aguda",
             "Mielofibrose aguda",
             "Outras leucemias especificadas",
             "Leucemia aguda de tipo celular não especificado",
             "Leucemia crônica de tipo celular não especificado",
             "Leucemia subaguda de tipo celular não especificado",
             "Outras leucemias de tipo celular não especificado",
             "Leucemia não especificada",
             "Doença de Letterer-Siwe",
             "Histiocitose maligna",
             "Tumor maligno de mastócitos",
             "Linfoma histiocítico verdadeiro",
             "Outras neoplasias malignas especificadas dos tecidos linfático, hematopoético e tecidos correlatos",
             "Neoplasia maligna dos tecidos linfático, hematopoético e tecidos correlatos, não especificada",
             "Neoplasias malignas de localizações múltiplas independentes (primárias)",
             "Carcinoma in situ dos lábios, cavidade oral e faringe",
             "Carcinoma in situ do esôfago",
             "Carcinoma in situ do estômago",
             "Carcinoma in situ do cólon",
             "Carcinoma in situ da junção retossigmóide",
             "Carcinoma in situ do reto",
             "Carcinoma in situ do ânus e canal anal",
             "Carcinoma in situ de outras partes do intestino e as não especificadas",
             "Carcinoma in situ do fígado, vesícula biliar e vias biliares",
             "Carcinoma in situ de outros órgãos especificados do aparelho digestivo",
             "Carcinoma in situ de órgãos digestivos, não especificado",
             "Carcinoma in situ da laringe",
             "Carcinoma in situ da traquéia",
             "Carcinoma in situ dos brônquios e pulmões",
             "Carcinoma in situ de outras partes do aparelho respiratório",
             "Carcinoma in situ do aparelho respiratório, não especificado",
             "Melanoma in situ do lábio",
             "Melanoma in situ da pálpebra, incluindo o canto",
             "Melanoma in situ da orelha e do conduto auditivo externo",
             "Melanoma in situ de outras partes, e de partes não especificadas da face",
             "Melanoma in situ do couro cabeludo e do pescoço",
             "Melanoma in situ do tronco",
             "Melanoma in situ dos membros superiores, incluindo ombro",
             "Melanoma in situ dos membros inferiores, incluindo quadril",
             "Melanoma in situ de outras localizações",
             "Melanoma in situ, não especificado",
             "Carcinoma in situ da pele do lábio",
             "Carcinoma in situ da pele da pálpebra, incluindo o canto",
             "Carcinoma in situ da pele da orelha e do conduto auditivo externo",
             "Carcinoma in situ da pele de outras partes e de partes não especificadas da face",
             "Carcinoma in situ da pele do couro cabeludo e do pescoço",
             "Carcinoma in situ da pele do tronco",
             "Carcinoma in situ da pele dos membros superiores, incluindo ombro",
             "Carcinoma in situ da pele dos membros inferiores, incluindo quadril",
             "Carcinoma in situ da pele de outras localizações",
             "Carcinoma in situ da pele, não especificada",
             "Carcinoma lobular in situ",
             "Carcinoma intraductal in situ",
             "Outros carcinomas in situ",
             "Carcinoma in situ da mama, não especificado",
             "Carcinoma in situ do endocérvix",
             "Carcinoma in situ do exocérvix",
             "Carcinoma in situ de outras partes do colo do útero",
             "Carcinoma in situ do colo do útero, não especificado",
             "Carcinoma in situ do endométrio",
             "Carcinoma in situ da vulva",
             "Carcinoma in situ da vagina",
             "Carcinoma in situ de outros órgãos genitais femininos e os não especificados",
             "Carcinoma in situ do pênis",
             "Carcinoma in situ da próstata",
             "Carcinoma in situ de outros órgãos genitais masculinos e os não especificados",
             "Carcinoma in situ da bexiga",
             "Carcinoma in situ de outros órgãos urinários e os não especificados",
             "Carcinoma in situ do olho",
             "Carcinoma in situ da tireóide e de outras glândulas endócrinas",
             "Carcinoma in situ de outras localizações especificadas",
             "Carcinoma in situ, não especificado",
             "Neoplasia benigna dos lábios",
             "Neoplasia benigna da língua",
             "Neoplasia benigna do assoalho da boca",
             "Neoplasia benigna de outras partes da boca e as não especificadas",
             "Neoplasia benigna da amígdala",
             "Neoplasia benigna de outras partes da orofaringe",
             "Neoplasia benigna da nasofaringe",
             "Neoplasia benigna da hipofaringe",
             "Neoplasia benigna da faringe, não especificada",
             "Neoplasia benigna da glândula parótida",
             "Neoplasia benigna de outras glândulas salivares maiores",
             "Neoplasia benigna da glândula salivar maior, não especificada",
             "Neoplasia benigna do ceco",
             "Neoplasia benigna do apêndice (vermiforme)",
             "Neoplasia benigna do cólon ascendente",
             "Neoplasia benigna do cólon transverso",
             "Neoplasia benigna do cólon descendente",
             "Neoplasia benigna do cólon sigmóide",
             "Neoplasia benigna do cólon, não especificada",
             "Neoplasia benigna da junção retossigmóide",
             "Neoplasia benigna do reto",
             "Neoplasia benigna do canal anal e ânus",
             "Neoplasia benigna do esôfago",
             "Neoplasia benigna do estômago",
             "Neoplasia benigna do duodeno",
             "Neoplasia benigna de outras partes e partes não especificadas do intestino delgado",
             "Neoplasia benigna do fígado",
             "Neoplasia benigna das vias biliares extra-hepáticas",
             "Neoplasia benigna do pâncreas",
             "Neoplasia benigna do pâncreas endócrino",
             "Neoplasia benigna de localizações mal definidas do aparelho digestivo",
             "Neoplasia benigna do ouvido médio, cavidade nasal e seios paranasais",
             "Neoplasia benigna da laringe",
             "Neoplasia benigna da traquéia",
             "Neoplasia benigna dos brônquios e pulmão",
             "Neoplasia benigna do aparelho respiratório, não especificado",
             "Neoplasia benigna do timo",
             "Neoplasia benigna do coração",
             "Neoplasia benigna do mediastino",
             "Neoplasia benigna de outros órgãos intratorácicos especificados",
             "Neoplasia benigna de órgão intratorácico, não especificado",
             "Neoplasia benigna da omoplata [escápula] e ossos longos dos membros superiores",
             "Neoplasia benigna dos ossos curtos dos membros superiores",
             "Neoplasia benigna dos ossos longos dos membros inferiores",
             "Neoplasia benigna dos ossos curtos dos membros inferiores",
             "Neoplasia benigna dos ossos do crânio e da face",
             "Neoplasia benigna do osso da mandíbula",
             "Neoplasia benigna da coluna vertebral",
             "Neoplasia benigna das costelas, do esterno e da clavícula",
             "Neoplasia benigna dos ossos pélvicos, sacro e cóccix",
             "Neoplasia benigna do osso e cartilagem articular, não especificado",
             "Neoplasia lipomatosa benigna da pele e do tecido subcutâneo da cabeça, face e pescoço",
             "Neoplasia lipomatosa benigna da pele e tecido subcutâneo do tronco",
             "Neoplasia lipomatosa benigna da pele e tecido subcutâneo dos membros",
             "Neoplasia lipomatosa benigna da pele e tecido subcutâneo de outras localizações e de localizações não especificadas",
             "Neoplasia lipomatosa benigna de órgãos intratorácicos",
             "Neoplasia lipomatosa benigna de órgãos intra-abdominais",
             "Neoplasia lipomatosa benigna do cordão espermático",
             "Neoplasia lipomatosa benigna de outras localizações",
             "Neoplasia lipomatosa benigna de localização não especificada",
             "Hemangioma de qualquer localização",
             "Linfangioma de qualquer localização",
             "Neoplasia benigna do tecido mesotelial da pleura",
             "Neoplasia benigna do tecido mesotelial do peritônio",
             "Neoplasia benigna do tecido mesotelial de outras localizações",
             "Neoplasia benigna do tecido mesotelial, não especificado",
             "Neoplasia benigna do retroperitônio",
             "Neoplasia benigna do peritônio",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles da cabeça, face e pescoço",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles dos membros superiores, incluindo ombro",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles dos membros inferiores, incluindo quadril",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles do tórax",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles do abdome",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles da pelve",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles do tronco, não especificado",
             "Neoplasia benigna do tecido conjuntivo e outros tecidos moles, sem outra especificação",
             "Nevo melanocítico do lábio",
             "Nevo melanocítico da pálpebra, incluindo o canto",
             "Nevo melanocítico da orelha e do conduto auditivo externo",
             "Nevo melanocítico de outras partes e de partes não especificadas da face",
             "Nevo melanocítico do couro cabeludo e do pescoço",
             "Nevo melanocítico do tronco",
             "Nevo melanocítico dos membros superiores, incluindo ombro",
             "Nevo melanocítico dos membros inferiores, incluindo quadril",
             "Nevo melanocítico, não especificado",
             "Neoplasia benigna da pele dos lábios",
             "Neoplasia benigna da pele da pálpebra, incluindo o canto",
             "Neoplasia benigna da pele da orelha e do conduto auditivo externo",
             "Neoplasia benigna da pele de outras partes e de partes não especificadas da face",
             "Neoplasia benigna da pele do couro cabeludo e do pescoço",
             "Neoplasia benigna da pele do tronco",
             "Neoplasia benigna da pele dos membros superiores, incluindo o ombro",
             "Neoplasia benigna da pele dos membros inferiores, incluindo o quadril",
             "Neoplasia benigna da pele, não especificada",
             "Neoplasia benigna da mama",
             "Leiomioma submucoso do útero",
             "Leiomioma intramural do útero",
             "Leiomioma subseroso do útero",
             "Leiomioma do útero, não especificado",
             "Neoplasia benigna do colo do útero",
             "Neoplasia benigna do corpo do útero",
             "Neoplasia benigna de outras partes do útero",
             "Neoplasia benigna do útero, não especificado",
             "Neoplasia benigna do ovário",
             "Neoplasia benigna da vulva",
             "Neoplasia benigna da vagina",
             "Neoplasia benigna das trompas e ligamentos uterinos",
             "Neoplasia benigna de outros órgãos genitais femininos especificados",
             "Neoplasia benigna de órgão genital feminino, não especificado",
             "Neoplasia benigna do pênis",
             "Neoplasia benigna da próstata",
             "Neoplasia benigna dos testículos",
             "Neoplasia benigna do epidídimo",
             "Neoplasia benigna do escroto",
             "Neoplasia benigna de outros órgãos genitais masculinos",
             "Neoplasia benigna de órgão genital masculino, não especificado",
             "Neoplasia benigna do rim",
             "Neoplasia benigna da pelve renal",
             "Neoplasia benigna do ureter",
             "Neoplasia benigna da bexiga",
             "Neoplasia benigna da uretra",
             "Neoplasia benigna de outros órgãos urinários",
             "Neoplasia benigna de órgão urinário, não especificado",
             "Neoplasia benigna da conjuntiva",
             "Neoplasia benigna da córnea",
             "Neoplasia benigna da retina",
             "Neoplasia benigna da coróide",
             "Neoplasia benigna do corpo ciliar",
             "Neoplasia benigna das glândulas e dos canais lacrimais",
             "Neoplasia benigna da órbita, não especificada",
             "Neoplasia benigna do olho, não especificado",
             "Neoplasia benigna das meninges cerebrais",
             "Neoplasia benigna das meninges espinhais",
             "Neoplasia benigna das meninges, não especificada",
             "Neoplasia benigna do encéfalo, supratentorial",
             "Neoplasia benigna do encéfalo, infratentorial",
             "Neoplasia benigna do encéfalo, não especificado",
             "Neoplasia benigna dos nervos cranianos",
             "Neoplasia benigna da medula espinhal",
             "Neoplasia benigna de outras partes especificadas do sistema nervoso central",
             "Neoplasia benigna do sistema nervoso central, não especificado",
             "Neoplasia benigna da glândula tireóide",
             "Neoplasia benigna da glândula supra-renal (adrenal)",
             "Neoplasia benigna da glândula paratireóide",
             "Neoplasia benigna da glândula hipófise (pituitária)",
             "Neoplasia benigna do conduto craniofaríngeo",
             "Neoplasia benigna da glândula pineal",
             "Neoplasia benigna do corpo carotídeo",
             "Neoplasia benigna dos corpos aórticos e outros paragânglios",
             "Neoplasia benigna de outras glândulas endócrinas especificadas",
             "Neoplasia benigna com comprometimento pluriglandular",
             "Neoplasia benigna de glândula endócrina, não especificada",
             "Neoplasia benigna dos gânglios linfáticos (linfonodos)",
             "Neoplasia benigna dos nervos periféricos e sistema nervoso autônomo",
             "Neoplasia benigna de outras localizações especificadas",
             "Neoplasia benigna de localização não especificada",
             "Neoplasia de comportamento incerto ou desconhecido do lábio, cavidade oral e faringe",
             "Neoplasia de comportamento incerto ou desconhecido do estômago",
             "Neoplasia de comportamento incerto ou desconhecido do intestino delgado",
             "Neoplasia de comportamento incerto ou desconhecido do apêndice",
             "Neoplasia de comportamento incerto ou desconhecido dos cólons",
             "Neoplasia de comportamento incerto ou desconhecido do reto",
             "Neoplasia de comportamento incerto ou desconhecido do fígado, vesícula biliar e vias biliares",
             "Neoplasia de comportamento incerto ou desconhecido de outros órgãos digestivos",
             "Neoplasia de comportamento incerto ou desconhecido de órgão digestivo, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido da laringe",
             "Neoplasia de comportamento incerto ou desconhecido da traquéia, brônquios e pulmão",
             "Neoplasia de comportamento incerto ou desconhecido da pleura",
             "Neoplasia de comportamento incerto ou desconhecido do mediastino",
             "Neoplasia de comportamento incerto ou desconhecido do timo",
             "Neoplasia de comportamento incerto ou desconhecido de outros órgãos respiratórios",
             "Neoplasia de comportamento incerto ou desconhecido de órgão respiratório, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido do útero",
             "Neoplasia de comportamento incerto ou desconhecido do ovário",
             "Neoplasia de comportamento incerto ou desconhecido da placenta",
             "Neoplasia de comportamento incerto ou desconhecido de outros órgãos genitais femininos",
             "Neoplasia de comportamento incerto ou desconhecido de órgão genital feminino, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido da próstata",
             "Neoplasia de comportamento incerto ou desconhecido do testículo",
             "Neoplasia de comportamento incerto ou desconhecido de outros órgãos genitais masculinos",
             "Neoplasia de comportamento incerto ou desconhecido de órgão genital masculino, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido do rim",
             "Neoplasia de comportamento incerto ou desconhecido da pelve renal",
             "Neoplasia de comportamento incerto ou desconhecido do ureter",
             "Neoplasia de comportamento incerto ou desconhecido da uretra",
             "Neoplasia de comportamento incerto ou desconhecido da bexiga",
             "Neoplasia de comportamento incerto ou desconhecido de outros órgãos urinários",
             "Neoplasia de comportamento incerto ou desconhecido de órgão urinário, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido das meninges cerebrais",
             "Neoplasia de comportamento incerto ou desconhecido das meninges espinhais",
             "Neoplasia de comportamento incerto ou desconhecido de meninges não especificadas",
             "Neoplasia de comportamento incerto ou desconhecido do encéfalo, supratentorial",
             "Neoplasia de comportamento incerto ou desconhecido do encéfalo, infratentorial",
             "Neoplasia de comportamento incerto ou desconhecido do encéfalo, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido dos nervos cranianos",
             "Neoplasia de comportamento incerto ou desconhecido da medula espinhal",
             "Neoplasia de comportamento incerto ou desconhecido de outras partes do sistema nervoso central",
             "Neoplasia de comportamento incerto ou desconhecido do sistema nervoso central, não especificado",
             "Neoplasia de comportamento incerto ou desconhecido da glândula tireóide",
             "Neoplasia de comportamento incerto ou desconhecido da glândula supra-renal (adrenal)",
             "Neoplasia de comportamento incerto ou desconhecido da glândula paratireóide",
             "Neoplasia de comportamento incerto ou desconhecido da glândula hipófise (pituitária)",
             "Neoplasia de comportamento incerto ou desconhecido do conduto craniofaríngeo",
             "Neoplasia de comportamento incerto ou desconhecido da glândula pineal",
             "Neoplasia de comportamento incerto ou desconhecido do corpo carotídeo",
             "Neoplasia de comportamento incerto ou desconhecido dos corpos aórticos e outros paragânglios",
             "Neoplasia de comportamento incerto ou desconhecido com comprometimento pluriglandular",
             "Neoplasia de comportamento incerto ou desconhecido de glândula endócrina, não especificada",
             "Policitemia vera",
             "Anemia refratária sem sideroblastos",
             "Anemia refratária com sideroblastos",
             "Anemia refratária com excesso de blastos",
             "Anemia refratária com excesso de blastos com transformação",
             "Anemia refratária, não especificada",
             "Outras síndromes mielodisplásicas",
             "Síndrome mielodisplásica, não especificada",
             "Tumores de comportamento incerto ou desconhecido de mastócitos e células histiocíticas",
             "Doença mieloproliferativa crônica",
             "Gamopatia monoclonal",
             "Trombocitemia essencial (hemorrágica)",
             "Outras neoplasias especificadas de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos relacionados",
             "Neoplasia de comportamento incerto ou desconhecido dos tecidos linfático, hematopoético e tecidos correlatos, não especificada",
             "Neoplasia de comportamento incerto ou desconhecido dos ossos e cartilagens articulares",
             "Neoplasia de comportamento incerto ou desconhecido do tecido conjuntivo e outros tecidos moles",
             "Neoplasia de comportamento incerto ou desconhecido dos nervos periféricos e do sistema nervoso periférico",
             "Neoplasia de comportamento incerto ou desconhecido do retroperitônio",
             "Neoplasia de comportamento incerto ou desconhecido do peritônio",
             "Neoplasia de comportamento incerto ou desconhecido da pele",
             "Neoplasia de comportamento incerto ou desconhecido da mama",
             "Neoplasia de comportamento incerto ou desconhecido de outras localizações especificadas",
             "Neoplasia de comportamento incerto ou desconhecido sem outra especificação", "Pelve renal, não especificao", "Retossigmóide, não especificado", "Seio piriforme, não especificado",
             "Parótida, não especificado", "Base da língua, não especificado", "Timo, não especificado", "Vesícula biliar, não especificado", "Reto, não especificado", "Vagina, não especificado",
             "Útero, não especificado", "Ovário, não especificado", "Ovário, não especificado", "Local primário desconhecido", "Tireoide, não especificado", "Ureter", "Próstata, não especificado",
             "Neoplasia maligna da próstata", "Neoplasia maligna da próstata", "Rim, não especificado", "Neoplasia maligna do rim, exceto pelve renal", "Neoplasia maligna dos testículos",
             "Sistema hematopoiético, não especificado", "Baço", "Sangue", "Sistema reticuloendotelial, não especificado", "Mola hidatidiforme, não especificado")
  )

  # Verifica se a coluna Localizacao_Primaria_3D existe antes de tentar acessá-la
  if (!"Localizacao_Primaria_4D" %in% names(dados)) {
    stop("\033[1;31mA coluna 'Localizacao_Primaria_4D' não foi encontrada no dataframe. Função interrompida.\033[0m")
  }

  message("Mapeando os códigos CID-O de 4 dígitos para nomes completos.")
  # Mapeamento dos códigos CID para nomes usando um vetor nomeado
  map <- setNames(cid_names$NOME, cid_names$CID)
  dados$CID4d <- map[dados$Localizacao_Primaria_4D]
  message("Nomes completos dos CID-O de 4 dígitos adicionados.")

  message(paste("\033[1;32m", "> Ajuste dos códigos CID-O de 4 dígitos concluído com sucesso. Foi adicionada uma coluna no dataframe, chamada CID4d.", "\033[0m"))

  return(dados)
}


