#' Converte os Códigos CNES para os Nomes Completos.
#'
#' Esta função mapeia os códigos CNES para os nomes completos dos estabelecimentos na coluna `CNES_Hospital` de um dataframe. Os nomes completos dos estabelecimentos são adicionados em uma nova coluna `Estabelecimento_Hospitalar`.
#'
#' @param dados Um dataframe contendo a coluna `CNES_Hospital`.
#' @return Retorna um dataframe com os nomes completos dos estabelecimentos adicionados em uma nova coluna.
#' @export
#' @name renomear_CNES
#' @examples
#' # Escreva o nome do dataframe e execute a função. Se seu dataframe for "dados_RHC_combinados", use a função como:
#'
#' dados_RHC_combinados <- renomear_CNES(dados_RHC_combinados)
renomear_CNES <- function(dados) {
  message("Iniciando o ajuste dos códigos CNES para nomes completos dos estabelecimentos.")

  # Definição do dataframe de mapeamento de CNES para nomes dos estabelecimentos
  cnes_names <- data.frame(
    CNES = c("2001586", "2005417", "2007037", "2006197", "2006448", "2020645", "2012677", "2017644", "3400557",
             "6602533", "2601680", "2772280", "2525569", "2802112", "4028155", "0003808", "0003816", "0003786",
             "0003832", "0004278", "0003859", "0003921", "2802104", "2799286", "2301318", "2402076", "2772566",
             "2407205", "2564211", "2563681", "2561492", "2723220", "2651394", "2611686", "2497654", "2528843",
             "2723190", "3021114", "0010510", "0010499", "0010456", "0010464", "0010480", "0010472", "0010502",
             "6876617", "2547821", "2448521", "2465833", "2494442", "0011738", "0011800", "0011746", "4044916",
             "2442108", "2361787", "2506815", "2338424", "2338351", "7891067", "2531348", "6497489", "2697696",
             "2726653", "2646536", "2171945", "2098938", "2200457", "2695324", "0026859", "0027049", "0027014",
             "0026840", "0026964", "2126494", "2148293", "2159252", "2118661", "2205440", "2215586", "2105780",
             "2153025", "2153114", "2153106", "2149990", "2219646", "2195453", "2775999", "9650105", "6442560",
             "2209195", "2129469", "2110075", "2111640", "2127989", "3145425", "2161354", "2206528", "2184834",
             "2165058", "2206595", "2146355", "6601804", "2761092", "0009709", "0009776", "0009725", "0009717",
             "2376334", "6201059", "6583326", "2756951", "2534444", "2659107", "2655519", "2396866", "2795671",
             "2334321", "7871902", "2332981", "5585422", "2315793", "2676060", "2399776", "2399741", "2605473",
             "3369293", "2427419", "2639009", "9262407", "0000809", "0000477", "0000434", "0000582", "2427427",
             "0000396", "4009444", "2726998", "3285391", "7445571", "2439360", "2576341", "0013633", "0013838",
             "0013846", "0014109", "2737434", "2740338", "2384299", "0015563", "0015334", "0015644", "3075516",
             "0015245", "9130780", "2591049", "5373190", "2741989", "2781859", "2577623", "2743469", "2586797",
             "2586169", "0017868", "2686953", "7205686", "7845138", "2280051", "2278286", "2287250", "2287447",
             "2287285", "2278855", "0012556", "0012505", "2275562", "2268779", "2296241", "2269988", "2269384",
             "2269880", "2295423", "2269775", "2273659", "2269899", "2295415", "2269783", "2280167", "2296616",
             "7185081", "2295067", "2273454", "2269821", "2273462", "2292386", "2273748", "25186", "3675580",
             "2371707", "2409194", "2409151", "2656930", "8003629", "2653982", "6599877", "4001303", "2515377",
             "7068336", "2319659", "2261987", "2241021", "2266474", "2232014", "2262274", "2223538", "2223546",
             "2263858", "2707918", "2261057", "2252287", "2246988", "2246929", "2252694", "2253054", "2237601",
             "2262568", "2265052", "2237253", "2237571", "2232995", "2255936", "2244306", "2254611", "2244357",
             "2259907", "2248298", "2248204", "2232022", "2227932", "2248190", "2558246", "2558254", "2537788",
             "2758164", "19445", "2691841", "19283", "2691868", "3157245", "2522691", "2306336", "2560771",
             "2436469", "6048692", "2504332", "2543044", "2568713", "2521792", "2491710", "0002283", "2816210",
             "0002534", "2078775", "2082527", "2081253", "2083094", "2083604", "2090236", "2790602", "2748223",
             "2704900", "2081482", "2082128", "2079798", "2081490", "2089327", "2084163", "2705982", "2081512",
             "2754843", "2027186", "2085194", "7066376", "2083086", "2786435", "2716801", "2081458", "2025507",
             "2083116", "2080680", "2096498", "4049020", "2077434", "2087057", "2772310", "7400926", "2755130",
             "2030705", "2082187", "2080400", "2084414", "7361289", "2082888", "2080273", "0008923", "0008753",
             "2025752", "2080354", "2079720", "2025361", "2027356", "2082594", "2080931", "2084228", "2798298",
             "2077396", "0009601", "2748029", "5869412", "2078287", "2688573", "2077574", "2088576", "2078015",
             "2077531", "2071371", "2066572", "2077523", "2688689", "2080575", "2077477", "2077485", "2077590",
             "2089696", "2080125", "6123740", "2091755", "2081695", "2092298", "2708779", "2079321", "2079828",
             "3126838", "2749319", "2080664", "2600536", "2786117", "9255400", "0004251", "0001023", "2430843",
             "3477371", "2281821", "0019402", "0009369"),
    ESTABELECIMENTO = c("Hospital da Fundação Hospitalar Estadual do Acre",
                        "Complexo Hospitalar Manoel André - CHAMA",
                        "Hospital da Santa Casa de Misericórdia de Maceió",
                        "Hospital Universitário Alberto Antunes/Universidade Federal de Alagoas",
                        "Hospital do Açúcar/Fundação da Agro-Indústria de Açúcar e do Álcool de Alagoas- Hospital veredas",
                        "Hospital de Clínicas Dr. Alberto Lima",
                        "Hospital da Fundação Centro de Controle de Oncologia/CECON",
                        "Hospital Universitário Getúlio Vargas",
                        "Instituto de Mama do Amazonas - SENSUMED",
                        "Hospital Estadual da Criança",
                        "Hospital Dom Pedro de Alcântara/Santa Casa de Misericórdia de Feira de Santana",
                        "Hospital Calixto Midlej Filho",
                        "Hospital Manoel Novaes",
                        "Hospital São José Maternidade Santa Helena/Santa Casa de Mis.",
                        "Hospital Regional de Juazeiro",
                        "Hospital São Rafael/Fundação Monte Tabor",
                        "Hospital Professor Edgard Santos/Hospital Universitário MEC - Universidade Federal da Bahia/FAPEX",
                        "Hospital Aristidez Maltez/Liga Baiana Contra o Câncer",
                        "Hospital Santa Isabel/Santa Casa de Misericórdia da Bahia",
                        "Hospital Martagão Gesteira/Liga Álvaro Bahia Contra a Mortalidade Infantil",
                        "Hospital Geral Roberto Santos",
                        "Centro Estadual de Oncologia - CICAN",
                        "Hospital Santo Antônio/Obras Sociais Irmã Dulce",
                        "Hospital Maternidade Luiz Argolo- Irmandade da Sta Casa de Miser De S Ant de Jesus",
                        "Hospital Municipal de Teixeira de Freitas/Prefeitura Municipal de T. de Freitas",
                        "Hospital Geral de Vitória da Conquista",
                        "Conquista Assistência Medica LTDA/ONCO-MED RAC",
                        "Serviço de Assistência Médica de Urgencia S. A. (SAMUR)",
                        "Hospital e Maternidade São Vicente de Paulo",
                        "Hospital Infantil Albert Sabin",
                        "Hospital Universitário Walter Cantídio",
                        "Instituto de Câncer do Ceará",
                        "Hospital da Irmandade Beneficente Santa Casa de Misericórdia de Fortaleza",
                        "Hospital Cura D'ars/Beneficência Camiliana",
                        "HGF- Hospital Geral de Fortaleza/Secretaria de Estado da Saude",
                        "Hospital Distrital Dr. Fernandes Távora/Instituto Clínico de Fortaleza",
                        "Centro Regional Integrado de Oncologia/CRIO",
                        "Hospital da Santa Casa de Misericórdia de Sobral",
                        "Hospital Universitário de Brasília/Fundação da Universidade de Brasília",
                        "Hospital Regional de Taguatinga",
                        "Hospital de Base do Distrito Federal",
                        "Hospital Regional da Asa Norte",
                        "Hospital Regional de Ceilândia",
                        "Hospital Regional do Gama",
                        "Hospital Regional de Sobradinho",
                        "Hospital da Criança de Brasília Jose Alencar - HCB",
                        "Hospital Evangélico de Cachoeiro de Itapemirim",
                        "Hospital São José",
                        "Hospital Rio Doce",
                        "Hospital Evangélico de Vila Velha",
                        "Hospital Santa Rita de Cássia/Associação Feminina Educacional de Combate ao Câncer",
                        "Hospital Infantil Nossa Senhora da Glória",
                        "Hospital da Santa Casa de Misericórdia de Vitória",
                        "Hospital Universitário Cassiano Antônio de Moraes",
                        "Hospital Evangélico Anápolis/Fundação James Fanstone",
                        "Santa Casa de Misericórdia de Anápolis/Fundação de Assistencia Social de Anápolis",
                        "Hospital Araújo Jorge/Hospital do Câncer/Associação de Combate ao Câncer em Goiás",
                        "Hospital das Clínicas da Universidade Federal Goiás",
                        "Hospital da Santa Casa de Misericórdia de Goiânia",
                        "Hospital Regional de Caxias Dr Everaldo Ferreira Aragão",
                        "Hospital São Rafael",
                        "ONCORADIUM",
                        "Instituto Maranhense de Oncologia Aldenora Belo IMOAB/Fundação Antônio Jorge Dino",
                        "Hospital Universitário Federal do Maranhão (HUUFM)",
                        "Hospital Geral Tarquínio Lopes Filho/SES",
                        "Casa de Caridade de Alfenas Nossa Senhora do Perpétuo Socorro",
                        "Hospital Ibiapaba S/A",
                        "Hospital Luxemburgo/Associação dos Amigos do Hospital Mário Penna",
                        "Hospital da Baleia/Fundação Benjamin Guimarães",
                        "Hospital Felício Rocho/Fundação Felice Rosso",
                        "Hospital das Clínicas da UFMG",
                        "Hospital da Santa Casa de Misericórdia de Belo Horizonte",
                        "Hospital São Francisco de Assis",
                        "Hospital Alberto Cavalcanti/Fundação Hospitalar do Estado de Minas Gerais",
                        "Hospital Professor Osvaldo R. Franco/Prefeitura de Betim/Fundo Municipal de Betim",
                        "Hospital Imaculada Conceição",
                        "Hospital São João de Deus/Fundação Geraldo Corrêa",
                        "Hospital Bom Samaritano/Beneficência Social Bom Samaritano",
                        "Hospital Márcio Cunha/Fundação São Francisco Xavier",
                        "Hospital Nossa Senhora das Dores",
                        "Hospital Manoel Goncalves",
                        "Hospital Maria José Baeta Reis/ASCOMCER",
                        "Hospital Dr. João Felício S/A",
                        "Instituto Oncológico",
                        "Hospital da Santa Casa de Montes Claros/Irmandade Nossa Senhora das Mercês de Montes Claros",
                        "Hospital Dílson de Quadros Godinho/Fundação Dílson de Quadros Godinho",
                        "Hospital do Câncer de Muriaé/Fundação Cristiano Varella",
                        "Hospital da Santa Casa de Misericórdia de Passos",
                        "Santa Casa de Misericórdia de Patos de Minas",
                        "Centro Oncológico AZ/Patos de Minas/MG",
                        "Hospital Santa Casa de Patrocínio",
                        "Hospital da Santa Casa de Misericórdia de Poços de Caldas",
                        "Clínica Memorial",
                        "Hospital Nossa Senhora das Dores/Irmandade Hospital N. Sra das Dores",
                        "Hospital das Clinicas Samuel Libânio",
                        "Instituto Sul Mineiro de Oncologia",
                        "Hospital da Santa Casa de Misericórdia de São João Del Rei",
                        "Hospital Nossa Senhora das Graças",
                        "Hospital Bom Samaritano",
                        "Hospital Dr. Hélio Angotti/Associação de Combate ao Câncer do Brasil Central",
                        "Hospital Escola da Universidade Federal do Triângulo Mineiro - Universidade Federal do Triângulo Mineiro",
                        "Hospital de Clínicas de Uberlândia/Universidade Federal de Uberlândia",
                        "Hospital e Maternidade Municipal Dr. Odelmo Leão Carneiro",
                        "Hospital Bom Pastor/Fundação Hospitalar do Município de Varginha",
                        "Hospital Universitário Maria Aparecida Pedrossian/UFMS",
                        "Hospital do Câncer Professor Dr. Alfredo Abrão/Fundação Carmem Prudente de Mato Grosso do Sul",
                        "Hospital Regional de Mato Grosso do Sul/Fundação Serviços de Saúde de Mato Grosso do Sul",
                        "Hospital da Santa Casa/Associação Beneficente de Campo Grande",
                        "Santa Casa de Misericórdia de Corumbá/Associação Beneficente de Corumbá",
                        "Hospital CASSEMS Unidade Dourados",
                        "Centro de Tratamento de Câncer de Dourados",
                        "Hospital Nossa Senhora Auxiliadora de Três Lagoas",
                        "Hospital do Câncer de Mato Grosso/Associação Matogrossense de Combate ao Câncer - AMCC",
                        "Hospital Geral Universitário/Associação de Proteção a Maternidade e a Infância Cuiabá",
                        "Hospital da Sociedade Beneficente Santa Casa de Misericórdia de Cuiabá",
                        "Santa Casa de Misericórdia e Maternidade de Rondonópolis",
                        "Hospital Santo Antonio/Fundação de Saúde Comunitária de Sinop",
                        "Hospital Ofir Loyola",
                        "Hospital Oncológico Infantil Octávio Lobo",
                        "Hospital Universitário João de Barros Barreto",
                        "Hospital Regional do Baixo Amazonas Dr. Waldemar Penna",
                        "Hospital da Fundação Assistência da Paraíba/FAP",
                        "Hospital Universitário Alcides Carneiro/Universidade Federal de Campina Grande",
                        "Hospital São Vicente de Paula/Instituto Walfredo Guedes Pereira",
                        "Hospital Napoleão Laureano",
                        "Hospital Regional Dep. Janduhy Carneiro",
                        "Hospital Memorial de Arcoverde",
                        "Hospital Regional do Agreste Dr. Waldemiro Ferrreira/Fund. Saude Amaury de Medeiros",
                        "Casa de Saúde e Maternidade Nossa Senhora do Perpétuo Socorro",
                        "Hospital Dom Tomas",
                        "Hospital da Fundação de Hematologia e Hemoterapia de Pernambuco/HEMOPE",
                        "Hospital Universitário Oswaldo Cruz",
                        "Instituto de Medicina Integral Prof. Fernanda Figueira - IMIP",
                        "Hospital de Câncer de Pernambuco/Sociedade Pernambucana do Combate ao Câncer",
                        "Hospital Barão de Lucena/Fundação de Saúde Amaury de Medeiros",
                        "Hospital das Clínicas/Universidade Federal de Pernambuco",
                        "Maternidade Dr. Marques Bastos e Hospital Infantil Dr. Mirócles Véras",
                        "Hospital São Marcos/Sociedade Piauiense Combate ao Câncer",
                        "Hospital Universitário da Universidade Federal do Piaui",
                        "ONCOCENTER",
                        "Hospital da Providência/Província Brasileira da Congregação Irmãs Filhas da Caridade de São Vicente de Paulo",
                        "Hospital Regional João de Freitas/Associação Norte Paranaense de Combate ao Câncer ao Câncer",
                        "Hospital Angelina Caron/Sociedade Hospitalar Angelina Caron",
                        "Hospital São Lucas",
                        "Hospital do Rocio",
                        "Hospital Santa Casa de Misericórdia/Associação Beneficiente Hospitalar Santa Casa de Misericórdia",
                        "CEONC",
                        "Hospital do Câncer de Cascavel UOPECCAN",
                        "Hospital de Clínicas/Universidade Federal do Paraná",
                        "Hospital Infantil Pequeno Príncipe/Associação Hospitalar de Proteção à Infância Dr. Raul Carneiro",
                        "Hospital Santa Casa/Irmandade da Santa Casa de Misericórdia de Curitiba",
                        "Hospital Erasto Gaertner/Liga Paranaense de Combate ao Câncer",
                        "Hospital São Vicente",
                        "Hospital Universitário Evangélico Mackenzie",
                        "Clinica RADION",
                        "Hospital Ministro Costa Cavalcante/Fundação de Saúde Itaiguapy",
                        "CEONC",
                        "Hospital de Caridade São Vicente de Paulo",
                        "Hospital Universitário Regional Norte do Paraná/Universidade Estadual de Londrina",
                        "Instituto de Câncer de Londrina",
                        "Hospital e Maternidade Santa Rita",
                        "Centro de Oncologia e Radioterapia Santana Ltda",
                        "Hospital do Câncer de Maringá/Instituto de Oncologia e Hematologia Maringá SC Ltda",
                        "Hospital Policlínica Pato Branco AS",
                        "Hospital da Santa Casa de Misericórdia de Ponta Grossa",
                        "Instituto Sul Paranense de Radioterapia",
                        "UOPECCAN - Filial Umuarama",
                        "Santa Casa de Misericórdia de Barra Mansa",
                        "Hospital Santa Isabel",
                        "Sociedade Portuguesa de Beneficiencia de Campos",
                        "Hospital Universitário Álvaro Alvim",
                        "Hospital Dr. Beda",
                        "Hospital São José do Avaí/Conferência São José do Avaí",
                        "Hospital Municipal Orêncio de Freitas",
                        "Hospital Universitário Antônio Pedro - HUAP/UFF",
                        "Hospital Alcides Carneiro",
                        "Centro de Terapia Oncológica",
                        "Hospital Regional Darcy Vargas",
                        "Hospital dos Servidores do Estado",
                        "Hospital Geral do Andaraí",
                        "Hospital Geral de Bonsucesso",
                        "Hospital Federal Cardoso Fontes",
                        "Hospital Geral de Ipanema",
                        "Hospital Geral da Lagoa",
                        "Hospital Mário Kroeff",
                        "Hospital Universitário Gaffrée e Guinle",
                        "Hospital Universitário Pedro Ernesto-HUPE/UERJ",
                        "Hospital Universitário Clementino Fraga Filho/UFRJ",
                        "Instituto de Puericultura e Pediatria Martagão Gesteira/UFRJ",
                        "Hospital Estadual Transplante Câncer e Cirurgia Infantil",
                        "Instituto Estadual de Hematologia Arthur Siqueira Cavalcanti",
                        "Instituto Nacional de Câncer/INCA - Hospital de Câncer I",
                        "Instituto Nacional de Câncer/INCA - Hospital de Câncer II",
                        "Instituto Nacional de Câncer/INCA - Hospital de Câncer III",
                        "Hospital São José/Associação Congregação de Santa Catarina",
                        "Hospital Universitário de Vassouras",
                        "Hospital Jardim Amália Ltda - HINJA",
                        "Hospital da LMECC",
                        "Hospital Wilson Rosado",
                        "Hospital Dr. Luiz Antônio/Liga Norteriograndense Contra o Câncer",
                        "Hospital Infantil Varela Santiago",
                        "Hospital Rio Grande",
                        "Hospital do Coração de Natal Ltda",
                        "Hospital Universitário Onofre Lopes - HUOL",
                        "Hospital Regional de Cacoal - HRC",
                        "Hospital de Base Dr. Ary Pinheiro/Hospital de Base Porto Velho",
                        "Instituto de Oncologia e Radioterapia São Pellegrino",
                        "Hospital de Amor da Amazônia",
                        "Hospital Geral de Roraima/HGR",
                        "Santa Casa de Caridade de Bagé",
                        "Hospital Tacchini",
                        "Hospital Caridade Beneficência Cachoeira do Sul",
                        "Hospital Nossa Senhora das Graças",
                        "Hospital de Caridade e Beneficência",
                        "Hospital Geral/Fundação UCS Hospital Geral de Caxias do Sul",
                        "Hospital Pompéia",
                        "Hospital São Vicente de Paulo/Associação das Damas de Caridade",
                        "Hospital da Fundação Hospitalar Santa Terezinha de Erechim",
                        "Hospital da Associação Hospital de Caridade de Ijuí",
                        "Hospital Bruno Born",
                        "Hospital São Vicente de Paulo",
                        "Hospital de Clínicas de Passo Fundo",
                        "Hospital Escola da UFPEL",
                        "Hospital da Santa Casa de Misericórdia de Pelotas",
                        "Hospital de Clínicas de Porto Alegre",
                        "Hospital São Lucas da PUCRS",
                        "Hospital Fêmina S/A",
                        "Hospital da Santa Casa de Misericórdia de Porto Alegre",
                        "Hospital Nossa Senhora da Conceição S/A",
                        "Santa Casa do Rio Grande",
                        "Hospital Ana Nery",
                        "Hospital Universitário de Santa Maria",
                        "Hospital Vida Saúde",
                        "Hospital de Caridade de Santiago",
                        "Hospital Santo Angelo",
                        "Hospital Ivan Goulart",
                        "Santa Casa de São Gabriel",
                        "Hospital Centenário",
                        "Hospital Bom Jesus",
                        "Santa Casa de Uruguaiana",
                        "Hospital Santa Isabel",
                        "Hospital Santo Antonio",
                        "Hospital Regional do Oeste",
                        "Hospital São José/Sociedade Caritativa Santo Agostinho",
                        "Centro de Pesquisas Oncológicas/CEPON",
                        "Hospital Governador Celso Ramos",
                        "Hospital Carmela Dutra",
                        "Hospital Infantil Joana de Gusmão",
                        "Hospital Univ. Professor Polydoro Ernani de São Thiago",
                        "Hospital e Maternidade Marieta Konder Bornhausen",
                        "Hospital São José/Sociedade Divina Providência",
                        "Hospital Universitário Santa Terezinha",
                        "Hospital Municipal São José",
                        "Hospital Materno Infantil Dr. Jesser Amarante Faria",
                        "Hospital e Maternidade Tereza Ramos",
                        "Hospital de Caridade São Braz de Porto União",
                        "Hospital Regional Alto Vale",
                        "Hospital e Maternidade Sagrada Família",
                        "Hospital Nossa Senhora da Conceição/Sociedade Divina Providência",
                        "Hospital de Cirurgia/Fundação de Beneficência Hospital de Cirurgia",
                        "Hospital Governador João Alves Filho",
                        "Hospital Universitário De Sergipe Huse",
                        "Hospital Sagrado Coração de Jesus/Santa Casa de Misericórdia de Araçatuba",
                        "Santa Casa de Araraquara",
                        "Hospital São Luiz de Araras",
                        "Hospital Regional de Assis",
                        "Santa Casa de Avaré",
                        "Fundação Pio XII Barretos",
                        "Hospital Estadual de Bauru",
                        "Hospital das Clínicas da Faculdade de Medicina de Botucatu",
                        "Hospital Universitário São Francisco na Prov. De Deus",
                        "Boldrini Campinas",
                        "Hospital e Maternidade Celso Pierro",
                        "Hospital das Clínicas da UNICAMP",
                        "Hospital Municipal Dr. Mário Gatti",
                        "Hospital Padre Albino Catanduva",
                        "Hospital Estadual de Diadema – Hospital Serraria",
                        "Santa Casa de Franca",
                        "Santa Casa de Misericórdia de Guaratinguetá",
                        "Hospital Santo Amaro",
                        "Santa Casa de Misericórdia de Itapeva",
                        "Hospital São Francisco de Assis",
                        "Hospital de Amor Jales",
                        "Hospital Amaral Carvalho",
                        "HCSVP Hospital São Vicente",
                        "GRENDACC",
                        "Santa Casa de Limeira",
                        "Hospital das Clínicas HCFAMEMA",
                        "Santa Casa de Marília",
                        "Hospital das Clínicas Luzia de Pinho Melo",
                        "Hospital Municipal Dr. Tabajara Ramos",
                        "Santa Casa de Ourinhos",
                        "Hospital Regional Dr. Leopoldo Bevilacqua",
                        "Hospital Fornecedores de Cana de Piracicaba",
                        "Santa Casa de Piracicaba",
                        "Fundação Hospital Regional do Câncer",
                        "Hospital Domingos Leonardo Cerávolo Presidente Prudente",
                        "Instituto de Radioterapia de Presidente Prudente",
                        "Hospital das Clínicas FAEPA",
                        "Hospital Imaculada Conceição",
                        "Santa Casa de Ribeirão Preto",
                        "CTR",
                        "Santa Casa de Rio Claro",
                        "Hospital Estadual Mário Covas de Santo André",
                        "Centro Hospitalar de Santo André Dr. Newton da Costa Brandão",
                        "Instituto de Radioterapia do ABC",
                        "Santa Casa de Santos",
                        "Hospital Santo Antônio Santos",
                        "Hospital Guilherme Álvaro",
                        "Hospital Anchieta",
                        "Hospital Municipal Universitário",
                        "Complexo Hospitalar Municipal",
                        "Santa Casa de São Carlos",
                        "Hospital da Santa Casa de Misericórdia Dona Carolina Malheiros",
                        "Santa Casa de Misericórdia de São José do Rio Preto",
                        "Hospital de Base de São José do Rio Preto",
                        "Hospital Pio XII",
                        "Santa Casa de Misericórdia",
                        "Centro de Tratamento Fabiana Macedo de Morais",
                        "Centro de Referência da Saúde da Mulher",
                        "Hospital Geral de Vila Nova Cachoeirinha",
                        "Conjunto Hospitalar do Mandaqui",
                        "Hosp de Transp. do Estado de SP Eurycles de Jesus Zerbini",
                        "HC da FMUSP Hopsital das Clínicas São Paulo",
                        "A C Camargo Cancer Center",
                        "Hospital Infantil Darcy Vargas UGA III São Paulo",
                        "Hospital Heliópolis",
                        "Hospital Ipiranga/Unidade de Gestão Assistencial II",
                        "Santa Casa de São Paulo Hospital Central São Paulo",
                        "Hospital BP/Real e Benemérita Associação Portuguesa de Beneficencia",
                        "Hospital Santa Marcelina São Paulo",
                        "Hospital São Paulo Hospital de Ensino da UNIFESP",
                        "IBCC",
                        "Hospital GRAACC Instituto de Oncologia Pediátrica IOP",
                        "Instituto do Câncer Arnaldo Vieira de Carvalho",
                        "Instituto do Câncer do Estado de São Paulo/SES",
                        "Hospital Geral de Vila Penteado Dr Jose Pangella São Paulo",
                        "Conjunto Hospitalar de Sorocaba",
                        "Santa Casa de Itu",
                        "Santa Casa de Sorocaba",
                        "Hospital GPACI",
                        "Hospital Geral de Pirajussara",
                        "Hospital Regional do Vale do Paraíba/Sociedade Beneficente São Camilo",
                        "Hospital Municipal Universitário de Taubaté",
                        "Santa Casa",
                        "Hospital de Regional de Araguaína",
                        "Hospital Geral de Palmas",
                        "Clínica Irradiar",
                        "Hospital Português/Real Sociedade Portuguesa de Beneficiência",
                        "Instituto de Radium e Supervoltagem Ivo Roesler/IRSIR",
                        "Instituto de Radioterapia Waldemir Miranda LTDA/IRWAM",
                        "Clínica de Radioterapia Ingá",
                        "Instituto Oncológico LTDA",
                        "Irmandade do Senhor Jesus dos Passos e Hospital de Caridade",
                        "Instituto de Radioterapia Vale do Paraíba/CENON - Centro de Oncologia Radioterápica do Vale do Paraíba")
  )

  # Verifica se a coluna CNES_Hospital existe antes de tentar acessá-la
  if ("CNES_Hospital" %in% names(dados)) {
    message("Mapeando os códigos CNES para nomes completos dos estabelecimentos.")
    # Mapeamento dos códigos CNES para nomes usando um vetor nomeado
    map <- setNames(cnes_names$ESTABELECIMENTO, cnes_names$CNES)
    dados$Estabelecimento_Hospitalar <- map[dados$CNES_Hospital]
    message("Nomes completos dos estabelecimentos adicionados.")
  } else {
    stop("\033[1;31mA coluna 'CNES_Hospital' não foi encontrada no dataframe. Função interrompida.\033[0m")
  }

  message(paste("\033[1;32m", "> Ajuste dos códigos CNES concluído com sucesso. Foi adicionada uma coluna no dataframe, chamada Estabelecimento_Hospitalar.", "\033[0m"))

  return(dados)
}


